### ISSUE TITLE
Cannot locate (file name).wav

### ISSUE THREAD

**Issue by Ctrl-Alt-Rage** [uberduck-ai/uberduck-ml-dev#167]
When I run the training script it seems to go well but then it says it cannot locate one of the wav files. 

I've gone into the filelist and tried removing the entries but it would just keep listing another wav not being able yo be located.

I've made sure my config has the correct paths to everything and I've verified multiple times the wav files are there.

What other potential solutions could I try?

**Comment by Ctrl-Alt-Rage** [comment]
Disregard - in the filelist I had to put the absolute path of the file names in the first column as well. But now I am faced with a:

> ython -m uberduck_ml_dev.exec.train_tacotron2 --config "tacotron2_config.json"
TTSTrainer start 17361.637707969
Initializing trainer with hparams:
{'attention_dim': 128,
 'attention_location_kernel_size': 31,
 'attention_location_n_filters': 32,
 'attention_rnn_dim': 1024,
 'audio_encoder_dim': 192,
 'audio_encoder_path': None,
 'batch_size': 18,
 'checkpoint_name': 'morgan_freeman',
 'checkpoint_path': 'checkpoints',
 'coarse_n_frames_per_step': None,
 'config': 'tacotron2_config.json',
 'cudnn_enabled': True,
 'dataset_path': '.',
 'debug': False,
 'decoder_rnn_dim': 1024,
 'distributed_run': False,
 'encoder_embedding_dim': 512,
 'encoder_kernel_size': 5,
 'encoder_n_convolutions': 3,
 'epochs': 5001,
 'epochs_per_checkpoint': 10,
 'filter_length': 1024,
 'fp16_run': False,
 'gate_threshold': 0.5,
 'get_gst': None,
 'grad_clip_thresh': 1.0,
 'gst_dim': 2304,
 'gst_type': 'torchmoji',
 'has_speaker_embedding': True,
 'hop_length': 256,
 'ignore_layers': ['speaker_embedding.weight'],
 'include_f0': False,
 'is_validate': True,
 'learning_rate': 0.0005,
 'load_f0s': False,
 'load_gsts': False,
 'log_dir': 'runs',
 'lr_decay_min': 1e-05,
 'lr_decay_rate': 216000,
 'lr_decay_start': 15000,
 'mask_padding': True,
 'max_decoder_steps': 1000,
 'max_wav_value': 32768.0,
 'mel_fmax': 8000.0,
 'mel_fmin': 0.0,
 'n_frames_per_step_initial': 1,
 'n_mel_channels': 80,
 'n_speakers': 1,
 'num_heads': 8,
 'num_workers': 1,
 'p_arpabet': 0.0,
 'p_attention_dropout': 0.1,
 'p_decoder_dropout': 0.1,
 'p_teacher_forcing': 1.0,
 'pin_memory': True,
 'pos_weight': None,
 'postnet_embedding_dim': 512,
 'postnet_kernel_size': 5,
 'postnet_n_convolutions': 5,
 'prenet_dim': 256,
 'ref_enc_filters': [32, 32, 64, 64, 128, 128],
 'ref_enc_gru_size': 128,
 'ref_enc_pad': [1, 1],
 'ref_enc_size': [3, 3],
 'ref_enc_strides': [2, 2],
 'sample_inference_speaker_ids': [0],
 'sample_inference_text': 'That quick beige fox jumped in the air loudly over '
                          'the thin dog fence.',
 'sample_rate': 22050,
 'sampling_rate': 22050,
 'seed': 123,
 'speaker_embedding_dim': 128,
 'steps_per_sample': 50,
 'symbol_set': 'nvidia_taco2',
 'symbols_embedding_dim': 512,
 'text_cleaners': ['english_cleaners'],
 'torchmoji_model_file': '/home/rage/CodingProjects/uberduck-ml-dev-master/pytorch_model.bin',
 'torchmoji_vocabulary_file': '/home/rage/CodingProjects/uberduck-ml-dev-master/vocabulary.json',
 'training_audiopaths_and_text': '/home/rage/CodingProjects/uberduck-ml-dev-master/project/wavs/filelist.txt',
 'val_audiopaths_and_text': '/home/rage/CodingProjects/uberduck-ml-dev-master/project/wavs/filelist.txt',
 'warm_start_name': '/home/rage/CodingProjects/uberduck-ml-dev-master/tacotron2_statedict.pt',
 'weight_decay': 1e-06,
 'win_length': 1024,
 'with_audio_encoding': False,
 'with_f0s': False,
 'with_gsts': False}
start train 17362.749267318
Initialized Torchmoji GST
Starting warm_start 17364.610595222
WARNING! Attempting to load a model with out the speaker_embedding.weight layer. This could lead to unexpected results during evaluation.
WARNING! Attempting to load a model with out the spkr_lin.weight layer. This could lead to unexpected results during evaluation.
WARNING! Attempting to load a model with out the spkr_lin.bias layer. This could lead to unexpected results during evaluation.
WARNING! Attempting to load a model with out the gst_lin.weight layer. This could lead to unexpected results during evaluation.
WARNING! Attempting to load a model with out the gst_lin.bias layer. This could lead to unexpected results during evaluation.
Ending warm_start 17364.657873166
Exception raised while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.81 GiB total capacity; 3.64 GiB already allocated; 10.44 MiB free; 3.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/exec/train_tacotron2.py", line 46, in <module>
    run(None, None, hparams)
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/exec/train_tacotron2.py", line 27, in run
    raise e
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/exec/train_tacotron2.py", line 23, in run
    trainer.train()
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/trainer/tacotron2.py", line 475, in train
    model_output = model(
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/models/tacotron2.py", line 249, in forward
    mel_outputs, gate_predicted, alignments = self.decoder(
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rage/anaconda3/envs/test-env/lib/python3.10/site-packages/uberduck_ml_dev/models/components/decoders/tacotron2.py", line 300, in forward
    mel_outputs = torch.cat(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.81 GiB total capacity; 3.64 GiB already allocated; 10.44 MiB free; 3.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by sjkoelle** [comment]
How could we make the tutorial more clear?

**Comment by Ctrl-Alt-Rage** [comment]
To be honest - I am not entirely sure. I know a lot of it has to do with my unfamiliarity with it. But I know that my biggest struggle is getting anything to train properly.
